# Jekyll Config
exclude: ['node_modules', 'gulpfile.js', 'README.md', 'fontcustom.yml','_less']
markdown: redcarpet
source: source
destination: build

# Server Config
host: mattfelten.dev

# Site Config
title: Matt Felten
url: http://mattfelten.com
paginate: 99
permalink: pretty
author:
  name: 'Matt Felten'
  url: https://twitter.com/mattfelten
