# Jekyll Config
exclude: ['README.md']
markdown: redcarpet

# Server Config
host: mattfelten.dev

# Site Config
title: Matt Felten
url: http://mattfelten.com
paginate: 99
permalink: pretty
author:
  name: 'Matt Felten'
  url: https://twitter.com/mattfelten

# Sass Config
sass:
  sass_dir: assets/_sass
  style: compressed
