# Don't use tabs!
# Build Settings
exclude: ['less']

# Permalinks
permalink: pretty

# Setup
title: Matt Felten
url: http://articles.mattfelten.com

author:
  name: 'Matt Felten'
  url: https://twitter.com/mattfelten

paginate: 99
