# Don't use tabs!
# Build Settings
exclude: ['less', 'fontcustom.yml']
markdown: redcarpet

# Permalinks
permalink: pretty

# Setup
title: Matt Felten
url: http://mattfelten.com

author:
  name: 'Matt Felten'
  url: https://twitter.com/mattfelten

paginate: 99
